// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8n7hG6Tc619ht-x8VwzXPYCo9HILHCTY',
    appId: '1:638457051369:web:26aaa0fec1171540671878',
    messagingSenderId: '638457051369',
    projectId: 'thismed-app',
    authDomain: 'thismed-app.firebaseapp.com',
    storageBucket: 'thismed-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxsf-gSxczB8fWoI27JhiyfIMMoqRI9ZU',
    appId: '1:638457051369:android:a96af3ffeda623ae671878',
    messagingSenderId: '638457051369',
    projectId: 'thismed-app',
    storageBucket: 'thismed-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_BJT2xEMhe5dSJoFka2v1_VejLbQAOA',
    appId: '1:638457051369:ios:28f664abe6332753671878',
    messagingSenderId: '638457051369',
    projectId: 'thismed-app',
    storageBucket: 'thismed-app.appspot.com',
    iosBundleId: 'com.example.thismedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_BJT2xEMhe5dSJoFka2v1_VejLbQAOA',
    appId: '1:638457051369:ios:295a6f56ac0cdd6b671878',
    messagingSenderId: '638457051369',
    projectId: 'thismed-app',
    storageBucket: 'thismed-app.appspot.com',
    iosBundleId: 'com.example.thismedApp.RunnerTests',
  );
}
